### ISSUE TITLE
Implement Color Select Field from AdminLTE

### ISSUE THREAD

**Issue by ericholmer** [zebradog/drupal-8-theme-adminlte#23]
Allow users to preview the hex colors that are added to the color fields.

![screen shot 2016-01-06 at 9 30 07 am](https://cloud.githubusercontent.com/assets/7988403/12146221/1afa18de-b458-11e5-8a08-b55a02e89ed5.png)

**Comment by matt-schuh** [comment]
I can't find any documentation on creating a widget for an existing field.  All documentation point to creating a whole new field and a widget to go with it.  I was hoping to be able to add a color widget to text fields to grab hex codes so that the data wouldn't have to be re-entered, however if I can't find documentation on adding a widget to an existing field this may not be an option.

**Comment by matt-schuh** [comment]
It may work to take the existing "color_field" module and add/edit a widget in there.  Currently, it would work but doesn't seem to have an option to type a hex code.  It has color pickers but no text input.  It would probably be fairly simple to edit that and swap a widget out for the AdminLTE colorpicker.
