### ISSUE TITLE
Make Select Fields Resizable

### ISSUE THREAD

**Issue by ericholmer** [zebradog/drupal-8-theme-adminlte#27]
This showed up in the "Project Services" field on the ZD site. 

Hard to see a long list with the imprecise scrolling offered by the small window. 

If you add "resize-vertical" to the class of the field the box can be dragged to see all the options. 

Select2 might address this as well...

**Comment by matt-schuh** [comment]
Added select2, and I'm trying to remember where we had the select boxes that needed resizing.  IIRC, it was only on multiple-select items since those were listed text box style instead of dropdown style.  If you can point me in the right direction, I can get select2 setup for these (multiple values select2).
